repos:
- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.12.0
  hooks:
    - id: reorder-python-imports
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-json
    - id: check-shebang-scripts-are-executable
    - id: detect-private-key
    - id: check-symlinks
    - id: pretty-format-json
    - id: requirements-txt-fixer
    - id: sort-simple-yaml
      files: .pre-commit-config
- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
    - id: black
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tflint
    - id: terraform_validate
    # - id: terraform_checkov
    - id: terraform_docs
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.38.0
  hooks:
  - id: markdownlint
