name: Python validation
on:  push:
    paths:
      - cloud_functions/**
    branches: [ "*" ]
  pull_request:
    paths:
      - cloud_functions/**
    branches: [ "*" ]
  workflow_dispatch:

concurrency:
  group: unique-execution

permissions:
  contents: read
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.7"
    - name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/genai-issue-actor/locations/global/workloadIdentityPools/github-terraformer/providers/gh-actions'
        service_account: 'tf-service-account@genai-issue-actor.iam.gserviceaccount.com'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test cloud_function with unittest
      env:
        PRIVATE_KEY: "c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDN056N3FiQzU4ZUorZFRjZGNIUTNURXQybzdSTFFiU3VvMWNLK2EvUnhGVklQQVI5VlB1UXJ3UFlmS1RwUGR2aVBHTFVIVXl2YXh0dGRpcXkveXcrVEFvOVRYYit6TEZBbjZoeGN5TXhQa2ZhYjhqYUZ2dGR4U2xzZDhieU5nMFAzbytONVVZaVdKMUZPRTFiMzREVjVJamFEekg2ZGlnclJHNUZKM1RLRkxvL2c4dVF3OFpCbHViOVcvNzRzcEFBd2I3QmRWdnQvcXcrcUxBaXJ2ODA4elY1SjlzcHpObkdaRU1pUlUxaTl6c1dNcURWQ2RzR0t5VnNyT1NpZVE2V0lXRkVIMWR2QWZpS2pIWWIwVDg3QVJvQWJ0RTN4N05NQnB5alRiVmgvWEc2MUwvZVdrZWQzYUZ5ckRxYTlxVStDdDNMVko1Mmx4VkhhcHhLSXEzT3IganZpbGxhcnJlYWwK"
        PUBLIC_KEY: "c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDN056N3FiQzU4ZUorZFRjZGNIUTNURXQybzdSTFFiU3VvMWNLK2EvUnhGVklQQVI5VlB1UXJ3UFlmS1RwUGR2aVBHTFVIVXl2YXh0dGRpcXkveXcrVEFvOVRYYit6TEZBbjZoeGN5TXhQa2ZhYjhqYUZ2dGR4U2xzZDhieU5nMFAzbytONVVZaVdKMUZPRTFiMzREVjVJamFEekg2ZGlnclJHNUZKM1RLRkxvL2c4dVF3OFpCbHViOVcvNzRzcEFBd2I3QmRWdnQvcXcrcUxBaXJ2ODA4elY1SjlzcHpObkdaRU1pUlUxaTl6c1dNcURWQ2RzR0t5VnNyT1NpZVE2V0lXRkVIMWR2QWZpS2pIWWIwVDg3QVJvQWJ0RTN4N05NQnB5alRiVmgvWEc2MUwvZVdrZWQzYUZ5ckRxYTlxVStDdDNMVko1Mmx4VkhhcHhLSXEzT3IganZpbGxhcnJlYWwK"
        PASS_KEY: "c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDN056N3FiQzU4ZUorZFRjZGNIUTNURXQybzdSTFFiU3VvMWNLK2EvUnhGVklQQVI5VlB1UXJ3UFlmS1RwUGR2aVBHTFVIVXl2YXh0dGRpcXkveXcrVEFvOVRYYit6TEZBbjZoeGN5TXhQa2ZhYjhqYUZ2dGR4U2xzZDhieU5nMFAzbytONVVZaVdKMUZPRTFiMzREVjVJamFEekg2ZGlnclJHNUZKM1RLRkxvL2c4dVF3OFpCbHViOVcvNzRzcEFBd2I3QmRWdnQvcXcrcUxBaXJ2ODA4elY1SjlzcHpObkdaRU1pUlUxaTl6c1dNcURWQ2RzR0t5VnNyT1NpZVE2V0lXRkVIMWR2QWZpS2pIWWIwVDg3QVJvQWJ0RTN4N05NQnB5alRiVmgvWEc2MUwvZVdrZWQzYUZ5ckRxYTlxVStDdDNMVko1Mmx4VkhhcHhLSXEzT3IganZpbGxhcnJlYWwK"
        GEMINI_API_KEY: "mock_gemini_api_key"
        GITHUB_PAT: "mock_github_pat"
        GENAI_MODEL: "gemini" 
      run: |
        pip install -r cloud_functions/event_handler/requirements.txt
        python -m unittest discover cloud_functions/event_handler
        pip install -r cloud_functions/event_processor/requirements.txt
        python -m unittest discover cloud_functions/event_processor/
