# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.7"
    - name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/genai-issue-actor/locations/global/workloadIdentityPools/github-terraformer/providers/gh-actions'
        service_account: 'tf-service-account@genai-issue-actor.iam.gserviceaccount.com'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r infrastructure/cloud_function/requirements.txt
    - name: Test with unittest
      run: |
        python -m unittest discover infrastructure/cloud_function/
