name: Python validation
on:
  push:
    paths:
      - cloud_functions/**
    branches: [ "*" ]
  pull_request:
    paths:
      - cloud_functions/**
    branches: [ "*" ]
  workflow_dispatch:

concurrency:
  group: unique-execution

permissions:
  contents: read
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.7"
    - name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/genai-issue-actor/locations/global/workloadIdentityPools/github-terraformer/providers/gh-actions'
        service_account: 'tf-service-account@genai-issue-actor.iam.gserviceaccount.com'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test cloud_function with unittest
      run: |
        pip install -r cloud_function/requirements.txt
        python -m unittest discover cloud_function/
        python -m unittest discover event_processor/
